# Slash Ping

ping-self: "&6Your ping is &c%ping% &6ms."
ping-others: "&c%name%&6's ping is &c%ping% &6ms."
ping-multiplier: 0.8

ping-syntax: "&cSyntax: /ping [name]"
no-permission: "&8(&4&l!&8) &6Unknown Command."

reload-config: "&6SlashPing Config Reloaded."