# SlashPing 1.0.6
# https://www.spigotmc.org/resources/112371/
# https://github.com/denniemok/slash-ping

# This plugin supports HEX codes on 1.16+ servers.
# Example: "#e69296Your ping is #c8a2c8%ping% #e69296ms."

ping-self: "&6Your ping is &c%ping% &6ms."
ping-others: "&c%name%&6's ping is &c%ping% &6ms."

## This message is triggered when the target is offline or has the exempt permission.
ping-failed: "&cError: &4You cannot ping that person."

# Formula: Normalised Ping =  Max ( Round ( Original Ping * Multiplier + Offset ), 0 )
# Both parameters can be either floats or integers. Offset can be negative.
ping-multiplier: 0.8
ping-offset: 0
ping-minimum: 0

ping-syntax: "&cSyntax: /ping [name]"
reload-syntax: "&cSyntax: /pingreload"

no-permission: "&8(&4&l!&8) &6Unknown Command."
no-permission-self: "&cYou do not have permission to ping yourself."
no-permission-others: "&cYou do not have permission to ping others."

reload-config: "&6SlashPing Config Reloaded."

# Don't forget to rate this resource! Have fun!
# Feel free to report any issues @ https://github.com/denniemok/slash-ping/issues.