name: SlashPing
main: com.battleasya.slashping.SlashPing
version: 1.0.6
author: Dennie
website: http://battleasya.com
description: Enables the checking of in-game ping with /ping.
commands:
  ping:
    description: Check in-game ping.
  pingreload:
    description: Reload config.
permissions:
  ping.*:
    default: op
    children:
      ping.self: true
      ping.others: true
      ping.reload: true
      ping.exempt: true
      ping.ignoreexempt: true