name: SlashPing
main: com.battleasya.slashping.SlashPing
version: 1.0.4
author: Dennie
website: http://battleasya.com
description: Minimalist Ping Plugin
commands:
  ping:
    description: Ping yourself.
  pingreload:
    description: Ping someone.
permissions:
  ping.*:
    default: op
    children:
      ping.self: true
      ping.others: true
      ping.reload: true
      ping.exempt: true
      ping.ignoreexempt: true